name: Build Repo
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Packages index (keep all versions)
        run: |
          cd debs
          dpkg-scanpackages . ../Packages
          gzip -k -f ../Packages

      - name: Commit generated files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Packages Packages.gz
          git commit -m "auto update repo index" || true
          git push
